Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Models/Tickets/CreateTicketModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketBookingSystem.Booking.Services;
using Autofac;
using TicketBookingSystem.Booking.BusinessObjects;
using System.ComponentModel.DataAnnotations;

namespace TicketBookingSystem.Web.Areas.Admin.Models.Tickets
{
    public class CreateTicketModel
    {
        [Required]
        public int CustomerId { get; set; }
        [Required,Range(100,40000,ErrorMessage ="Ticket Fee should be between " +
            "100 Taka and 40000 Taka")]
        public int TicketFee { get; set; }
        [Required]
        public string Destination { get; set; }

        private readonly ITicketService _ticketService;

        public CreateTicketModel()
        {
            _ticketService = Startup.AutofacContainer.Resolve<ITicketService>();
        }
        public CreateTicketModel(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        public void CreateTicket()
        {
            var ticket = new Ticket
            {
                CustomerId = CustomerId,
                TicketFee = TicketFee,
                Destination = Destination

            };
            _ticketService.CreateTicket(ticket);
        }
    }
}

Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Models/Tickets/EditTicketModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TicketBookingSystem.Booking.Services;
using Autofac;
using TicketBookingSystem.Booking.BusinessObjects;

namespace TicketBookingSystem.Web.Areas.Admin.Models.Tickets
{
    public class EditTicketModel
    {
        [Required]
        public int? Id { get; set; }
        [Required]
        public int? CustomerId { get; set; }
        [Required]
        public string Destination { get; set; }
        [Required]
        public int? TicketFee { get; set; }
        private readonly ITicketService _ticketService;

        public EditTicketModel()
        {
            _ticketService = Startup.AutofacContainer.Resolve<ITicketService>();
        }

        public EditTicketModel(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }
        public void LoadModelData(int id)
        {
            var ticket = _ticketService.GetTicket(id);
            Id = ticket?.Id;
            CustomerId = ticket?.CustomerId;
            Destination = ticket?.Destination;
            TicketFee = ticket?.TicketFee;

        }

        public void Update()
        {
            var ticket = new Ticket
            {
                Id = Id.HasValue ? Id.Value : 0,
                CustomerId = CustomerId.HasValue ? CustomerId.Value : 0,
                Destination = Destination,
                TicketFee = TicketFee.HasValue ? TicketFee.Value : 0
            };

            _ticketService.Update(ticket);
        }
    }
}

Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Models/Tickets/TicketListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketBookingSystem.Booking.Services;
using Autofac;
using TicketBookingSystem.Web.Models;

namespace TicketBookingSystem.Web.Areas.Admin.Models.Tickets
{
    public class TicketListModel
    {
        private readonly ITicketService _ticketService;

        public TicketListModel()
        {
            _ticketService = Startup.AutofacContainer.Resolve<ITicketService>();
        }
        public TicketListModel(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        internal object GetTicketInfo(DataTablesAjaxRequestModel tableModel)
        {
            var data = _ticketService.GetTickets(
                tableModel.PageIndex,
                tableModel.PageSize,
                tableModel.SearchText,
                tableModel.GetSortText(new string[] { "CustomerId", "Destination", "TicketFee" }));

            return new
            {
                recordsTotal = data.total,
                recordsFiltered = data.totalDisplay,
                data = (from record in data.records
                        select new string[]
                        {
                                record.CustomerId.ToString(),
                                record.Destination,
                                record.TicketFee.ToString(),
                                record.Id.ToString()
                        }
                    ).ToArray()
            };
        }

        public void Delete(int id)
        {
            _ticketService.Delete(id);
        }
    }
}

Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketBookingSystem.Web.Areas.Admin.Models.Tickets;
using TicketBookingSystem.Web.Models;

namespace TicketBookingSystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TicketController : Controller
    {
        private readonly ILogger<TicketController> _logger;
        public TicketController(ILogger<TicketController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            var model =new TicketListModel();
            return View();
        }
        public JsonResult GetTicketData()
        {
            var dataTableModel = new DataTablesAjaxRequestModel(Request);
            var model = new TicketListModel();
            var data = model.GetTicketInfo(dataTableModel);
            return Json(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Create(CreateTicketModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    model.CreateTicket();
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create a Ticket");
                    _logger.LogError(ex, "cannot create a ticket");
                }
            }
            return View();
        }

        public IActionResult Edit(int Id)
        {
            var model = new EditTicketModel();
            model.LoadModelData(Id);
            return View(model);

        }

        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Edit(EditTicketModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    model.Update();
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create a Ticket");
                    _logger.LogError(ex, "cannot create a ticket");
                }
            }
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Delete(int Id)
        {
            var model = new TicketListModel();
            model.Delete(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Views/Ticket/Create.cshtml
@model TicketBookingSystem.Web.Areas.Admin.Models.Tickets.CreateTicketModel
@{
    ViewData["Title"] = "Create";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Create A New Ticket</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Create Ticket</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Create A New Ticket</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Ticket"
                          asp-action="Create" asp-antiforgery="true">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="CustomerId" class="col-sm-2 col-form-label">Customer Id</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" asp-for="CustomerId" id="customerId"
                                           placeholder="Customer Id">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Destination" class="col-sm-2 col-form-label">Destination</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Destination" id="destination"
                                           placeholder="Destination">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="TicketFee" class="col-sm-2 col-form-label">Ticket Fee</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" asp-for="TicketFee" id="ticketFee"
                                           placeholder="Ticket Fee">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Create</button>
                            <a asp-controller="Ticket" asp-action="Index" class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Views/Ticket/Edit.cshtml
@model TicketBookingSystem.Web.Areas.Admin.Models.Tickets.EditTicketModel;
@{
    ViewData["Title"] = "Edit";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit A Ticket</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Edit Ticket</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Edit A Ticket</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Ticket"
                          asp-action="Edit" asp-antiforgery="true">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" asp-for="Id"/>
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="CustomerId" class="col-sm-2 col-form-label">Customer Id</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" asp-for="CustomerId" id="customerId"
                                           placeholder="Customer Id">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Destination" class="col-sm-2 col-form-label">Destination</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Destination" id="destination"
                                           placeholder="Destination">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="TicketFee" class="col-sm-2 col-form-label">Ticket Fee</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" asp-for="TicketFee" id="ticketFee"
                                           placeholder="Ticket Fee">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Edit</button>
                            <a asp-controller="Ticket" asp-action="Index" class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Assignment3/TicketBookingSystem/TicketBookingSystem.Web/Areas/Admin/Views/Ticket/Index.cshtml
@model TicketBookingSystem.Web.Areas.Admin.Models.Tickets.TicketListModel
@{
    ViewData["Title"] = "Index";
}

@section Styles
{
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
}
@section Scripts
{
    <script src="/admin/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $('#tickets').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/Ticket/GetTicketData",
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 3,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/ticket/edit/${data}'" value='${data}'>
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>`;
                        }
                    }
                ]
            });
            $('#tickets').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                $("#deleteId").val(id);
                $("#deleteForm").attr("action", "/admin/ticket/delete")
                modal.modal('show');
            });
            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });

    </script>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Available Tickets</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Tickets</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">All Available Tickets</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="tickets" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Customer Id</th>
                                    <th>Destination</th>
                                    <th>Ticket Fee</th>
                                    <th style="width:150px">Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Customer Id</th>
                                    <th>Destination</th>
                                    <th>Ticket Fee</th>
                                    <th style="width:150px">Action</th>
                                </tr>
                            </tfoot>
                        </table>
                        <partial name="_DeletePopUpPartial"/>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content-wrapper -->